// Generated by gencpp from file hw1/MultiplyTwoNums.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_MULTIPLYTWONUMS_H
#define HW1_MESSAGE_MULTIPLYTWONUMS_H

#include <ros/service_traits.h>


#include <hw1/MultiplyTwoNumsRequest.h>
#include <hw1/MultiplyTwoNumsResponse.h>


namespace hw1
{

struct MultiplyTwoNums
{

typedef MultiplyTwoNumsRequest Request;
typedef MultiplyTwoNumsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MultiplyTwoNums
} // namespace hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw1::MultiplyTwoNums > {
  static const char* value()
  {
    return "fa76f5fbe76a971f9b1d5d312793b2e8";
  }

  static const char* value(const ::hw1::MultiplyTwoNums&) { return value(); }
};

template<>
struct DataType< ::hw1::MultiplyTwoNums > {
  static const char* value()
  {
    return "hw1/MultiplyTwoNums";
  }

  static const char* value(const ::hw1::MultiplyTwoNums&) { return value(); }
};


// service_traits::MD5Sum< ::hw1::MultiplyTwoNumsRequest> should match
// service_traits::MD5Sum< ::hw1::MultiplyTwoNums >
template<>
struct MD5Sum< ::hw1::MultiplyTwoNumsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::MultiplyTwoNums >::value();
  }
  static const char* value(const ::hw1::MultiplyTwoNumsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::MultiplyTwoNumsRequest> should match
// service_traits::DataType< ::hw1::MultiplyTwoNums >
template<>
struct DataType< ::hw1::MultiplyTwoNumsRequest>
{
  static const char* value()
  {
    return DataType< ::hw1::MultiplyTwoNums >::value();
  }
  static const char* value(const ::hw1::MultiplyTwoNumsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw1::MultiplyTwoNumsResponse> should match
// service_traits::MD5Sum< ::hw1::MultiplyTwoNums >
template<>
struct MD5Sum< ::hw1::MultiplyTwoNumsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::MultiplyTwoNums >::value();
  }
  static const char* value(const ::hw1::MultiplyTwoNumsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::MultiplyTwoNumsResponse> should match
// service_traits::DataType< ::hw1::MultiplyTwoNums >
template<>
struct DataType< ::hw1::MultiplyTwoNumsResponse>
{
  static const char* value()
  {
    return DataType< ::hw1::MultiplyTwoNums >::value();
  }
  static const char* value(const ::hw1::MultiplyTwoNumsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW1_MESSAGE_MULTIPLYTWONUMS_H
