// Generated by gencpp from file hw1/Num.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_NUM_H
#define HW1_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw1
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : num(0.0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : num(0.0)  {
  (void)_alloc;
    }



   typedef double _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::hw1::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw1::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::hw1::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::hw1::Num > NumPtr;
typedef boost::shared_ptr< ::hw1::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw1::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw1::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw1::Num_<ContainerAllocator1> & lhs, const ::hw1::Num_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw1::Num_<ContainerAllocator1> & lhs, const ::hw1::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hw1::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw1::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw1::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw1::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f942a3e0cbd340847b2a0e5b31a783fe";
  }

  static const char* value(const ::hw1::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf942a3e0cbd34084ULL;
  static const uint64_t static_value2 = 0x7b2a0e5b31a783feULL;
};

template<class ContainerAllocator>
struct DataType< ::hw1::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw1/Num";
  }

  static const char* value(const ::hw1::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw1::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 num\n"
;
  }

  static const char* value(const ::hw1::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw1::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw1::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw1::Num_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<double>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW1_MESSAGE_NUM_H
