// Generated by gencpp from file fk/JointVariables.msg
// DO NOT EDIT!


#ifndef FK_MESSAGE_JOINTVARIABLES_H
#define FK_MESSAGE_JOINTVARIABLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fk
{
template <class ContainerAllocator>
struct JointVariables_
{
  typedef JointVariables_<ContainerAllocator> Type;

  JointVariables_()
    : q1(0.0)
    , q2(0.0)
    , q3(0.0)
    , q4(0.0)
    , q5(0.0)
    , q6(0.0)  {
    }
  JointVariables_(const ContainerAllocator& _alloc)
    : q1(0.0)
    , q2(0.0)
    , q3(0.0)
    , q4(0.0)
    , q5(0.0)
    , q6(0.0)  {
  (void)_alloc;
    }



   typedef double _q1_type;
  _q1_type q1;

   typedef double _q2_type;
  _q2_type q2;

   typedef double _q3_type;
  _q3_type q3;

   typedef double _q4_type;
  _q4_type q4;

   typedef double _q5_type;
  _q5_type q5;

   typedef double _q6_type;
  _q6_type q6;





  typedef boost::shared_ptr< ::fk::JointVariables_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fk::JointVariables_<ContainerAllocator> const> ConstPtr;

}; // struct JointVariables_

typedef ::fk::JointVariables_<std::allocator<void> > JointVariables;

typedef boost::shared_ptr< ::fk::JointVariables > JointVariablesPtr;
typedef boost::shared_ptr< ::fk::JointVariables const> JointVariablesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fk::JointVariables_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fk::JointVariables_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fk::JointVariables_<ContainerAllocator1> & lhs, const ::fk::JointVariables_<ContainerAllocator2> & rhs)
{
  return lhs.q1 == rhs.q1 &&
    lhs.q2 == rhs.q2 &&
    lhs.q3 == rhs.q3 &&
    lhs.q4 == rhs.q4 &&
    lhs.q5 == rhs.q5 &&
    lhs.q6 == rhs.q6;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fk::JointVariables_<ContainerAllocator1> & lhs, const ::fk::JointVariables_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fk::JointVariables_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fk::JointVariables_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fk::JointVariables_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fk::JointVariables_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fk::JointVariables_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fk::JointVariables_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fk::JointVariables_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a61a219e6f5b1a7fbfc4c6ce5b5c4482";
  }

  static const char* value(const ::fk::JointVariables_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa61a219e6f5b1a7fULL;
  static const uint64_t static_value2 = 0xbfc4c6ce5b5c4482ULL;
};

template<class ContainerAllocator>
struct DataType< ::fk::JointVariables_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fk/JointVariables";
  }

  static const char* value(const ::fk::JointVariables_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fk::JointVariables_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 q1\n"
"float64 q2\n"
"float64 q3\n"
"float64 q4\n"
"float64 q5\n"
"float64 q6\n"
;
  }

  static const char* value(const ::fk::JointVariables_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fk::JointVariables_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q1);
      stream.next(m.q2);
      stream.next(m.q3);
      stream.next(m.q4);
      stream.next(m.q5);
      stream.next(m.q6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointVariables_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fk::JointVariables_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fk::JointVariables_<ContainerAllocator>& v)
  {
    s << indent << "q1: ";
    Printer<double>::stream(s, indent + "  ", v.q1);
    s << indent << "q2: ";
    Printer<double>::stream(s, indent + "  ", v.q2);
    s << indent << "q3: ";
    Printer<double>::stream(s, indent + "  ", v.q3);
    s << indent << "q4: ";
    Printer<double>::stream(s, indent + "  ", v.q4);
    s << indent << "q5: ";
    Printer<double>::stream(s, indent + "  ", v.q5);
    s << indent << "q6: ";
    Printer<double>::stream(s, indent + "  ", v.q6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FK_MESSAGE_JOINTVARIABLES_H
