// Generated by gencpp from file pa1_scara/MoveLastJoint.msg
// DO NOT EDIT!


#ifndef PA1_SCARA_MESSAGE_MOVELASTJOINT_H
#define PA1_SCARA_MESSAGE_MOVELASTJOINT_H

#include <ros/service_traits.h>


#include <pa1_scara/MoveLastJointRequest.h>
#include <pa1_scara/MoveLastJointResponse.h>


namespace pa1_scara
{

struct MoveLastJoint
{

typedef MoveLastJointRequest Request;
typedef MoveLastJointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveLastJoint
} // namespace pa1_scara


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pa1_scara::MoveLastJoint > {
  static const char* value()
  {
    return "95da2541c9d6989c0876f480a9b1c7e4";
  }

  static const char* value(const ::pa1_scara::MoveLastJoint&) { return value(); }
};

template<>
struct DataType< ::pa1_scara::MoveLastJoint > {
  static const char* value()
  {
    return "pa1_scara/MoveLastJoint";
  }

  static const char* value(const ::pa1_scara::MoveLastJoint&) { return value(); }
};


// service_traits::MD5Sum< ::pa1_scara::MoveLastJointRequest> should match
// service_traits::MD5Sum< ::pa1_scara::MoveLastJoint >
template<>
struct MD5Sum< ::pa1_scara::MoveLastJointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pa1_scara::MoveLastJoint >::value();
  }
  static const char* value(const ::pa1_scara::MoveLastJointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa1_scara::MoveLastJointRequest> should match
// service_traits::DataType< ::pa1_scara::MoveLastJoint >
template<>
struct DataType< ::pa1_scara::MoveLastJointRequest>
{
  static const char* value()
  {
    return DataType< ::pa1_scara::MoveLastJoint >::value();
  }
  static const char* value(const ::pa1_scara::MoveLastJointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pa1_scara::MoveLastJointResponse> should match
// service_traits::MD5Sum< ::pa1_scara::MoveLastJoint >
template<>
struct MD5Sum< ::pa1_scara::MoveLastJointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pa1_scara::MoveLastJoint >::value();
  }
  static const char* value(const ::pa1_scara::MoveLastJointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa1_scara::MoveLastJointResponse> should match
// service_traits::DataType< ::pa1_scara::MoveLastJoint >
template<>
struct DataType< ::pa1_scara::MoveLastJointResponse>
{
  static const char* value()
  {
    return DataType< ::pa1_scara::MoveLastJoint >::value();
  }
  static const char* value(const ::pa1_scara::MoveLastJointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PA1_SCARA_MESSAGE_MOVELASTJOINT_H
