// Generated by gencpp from file pa1_scara/MoveLastJointResponse.msg
// DO NOT EDIT!


#ifndef PA1_SCARA_MESSAGE_MOVELASTJOINTRESPONSE_H
#define PA1_SCARA_MESSAGE_MOVELASTJOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pa1_scara
{
template <class ContainerAllocator>
struct MoveLastJointResponse_
{
  typedef MoveLastJointResponse_<ContainerAllocator> Type;

  MoveLastJointResponse_()
    {
    }
  MoveLastJointResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveLastJointResponse_

typedef ::pa1_scara::MoveLastJointResponse_<std::allocator<void> > MoveLastJointResponse;

typedef boost::shared_ptr< ::pa1_scara::MoveLastJointResponse > MoveLastJointResponsePtr;
typedef boost::shared_ptr< ::pa1_scara::MoveLastJointResponse const> MoveLastJointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace pa1_scara

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pa1_scara::MoveLastJointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pa1_scara/MoveLastJointResponse";
  }

  static const char* value(const ::pa1_scara::MoveLastJointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::pa1_scara::MoveLastJointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveLastJointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pa1_scara::MoveLastJointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pa1_scara::MoveLastJointResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PA1_SCARA_MESSAGE_MOVELASTJOINTRESPONSE_H
