// Generated by gencpp from file pa1_scara/ReferencePosition.msg
// DO NOT EDIT!


#ifndef PA1_SCARA_MESSAGE_REFERENCEPOSITION_H
#define PA1_SCARA_MESSAGE_REFERENCEPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pa1_scara
{
template <class ContainerAllocator>
struct ReferencePosition_
{
  typedef ReferencePosition_<ContainerAllocator> Type;

  ReferencePosition_()
    : x(0)
    , y(0)
    , z(0)  {
    }
  ReferencePosition_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::pa1_scara::ReferencePosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pa1_scara::ReferencePosition_<ContainerAllocator> const> ConstPtr;

}; // struct ReferencePosition_

typedef ::pa1_scara::ReferencePosition_<std::allocator<void> > ReferencePosition;

typedef boost::shared_ptr< ::pa1_scara::ReferencePosition > ReferencePositionPtr;
typedef boost::shared_ptr< ::pa1_scara::ReferencePosition const> ReferencePositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pa1_scara::ReferencePosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pa1_scara::ReferencePosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pa1_scara::ReferencePosition_<ContainerAllocator1> & lhs, const ::pa1_scara::ReferencePosition_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pa1_scara::ReferencePosition_<ContainerAllocator1> & lhs, const ::pa1_scara::ReferencePosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pa1_scara

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pa1_scara::ReferencePosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pa1_scara::ReferencePosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pa1_scara::ReferencePosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pa1_scara::ReferencePosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa1_scara::ReferencePosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pa1_scara::ReferencePosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pa1_scara::ReferencePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95da2541c9d6989c0876f480a9b1c7e4";
  }

  static const char* value(const ::pa1_scara::ReferencePosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95da2541c9d6989cULL;
  static const uint64_t static_value2 = 0x0876f480a9b1c7e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::pa1_scara::ReferencePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pa1_scara/ReferencePosition";
  }

  static const char* value(const ::pa1_scara::ReferencePosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pa1_scara::ReferencePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y\n"
"int64 z\n"
;
  }

  static const char* value(const ::pa1_scara::ReferencePosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pa1_scara::ReferencePosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReferencePosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pa1_scara::ReferencePosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pa1_scara::ReferencePosition_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PA1_SCARA_MESSAGE_REFERENCEPOSITION_H
