SCARA:
# Publish all joint states ------------------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Position Controllers -----------------------------------------------------
  L2_to_end_effector_position_controller:
    type: effort_controllers/JointPositionController
    joint: L2_to_end_effector
    pid: {p: 0.1, i: 0, d: 20}
