// Generated by gencpp from file pa1/HT.msg
// DO NOT EDIT!


#ifndef PA1_MESSAGE_HT_H
#define PA1_MESSAGE_HT_H

#include <ros/service_traits.h>


#include <pa1/HTRequest.h>
#include <pa1/HTResponse.h>


namespace pa1
{

struct HT
{

typedef HTRequest Request;
typedef HTResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HT
} // namespace pa1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pa1::HT > {
  static const char* value()
  {
    return "41bf0543de79fcb6f767b6c9848b88ec";
  }

  static const char* value(const ::pa1::HT&) { return value(); }
};

template<>
struct DataType< ::pa1::HT > {
  static const char* value()
  {
    return "pa1/HT";
  }

  static const char* value(const ::pa1::HT&) { return value(); }
};


// service_traits::MD5Sum< ::pa1::HTRequest> should match
// service_traits::MD5Sum< ::pa1::HT >
template<>
struct MD5Sum< ::pa1::HTRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pa1::HT >::value();
  }
  static const char* value(const ::pa1::HTRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa1::HTRequest> should match
// service_traits::DataType< ::pa1::HT >
template<>
struct DataType< ::pa1::HTRequest>
{
  static const char* value()
  {
    return DataType< ::pa1::HT >::value();
  }
  static const char* value(const ::pa1::HTRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pa1::HTResponse> should match
// service_traits::MD5Sum< ::pa1::HT >
template<>
struct MD5Sum< ::pa1::HTResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pa1::HT >::value();
  }
  static const char* value(const ::pa1::HTResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pa1::HTResponse> should match
// service_traits::DataType< ::pa1::HT >
template<>
struct DataType< ::pa1::HTResponse>
{
  static const char* value()
  {
    return DataType< ::pa1::HT >::value();
  }
  static const char* value(const ::pa1::HTResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PA1_MESSAGE_HT_H
